'use client';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Box, Typography } from '@mui/material';
import './globals.css';
import { Provider } from 'react-redux';
import { setupStore } from '@/store/store';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const store = setupStore();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider store={store}>
          <Typography variant="h3" color="secondary" padding={2}>
            СТРОЙ МАРКЕТ
          </Typography>

          {children}
        </Provider>
      </body>
    </html>
  );
}
